### ISSUE TITLE
add question

### ISSUE THREAD

**Issue by alexandregrue** [WildCodeSchool/purple-php-2109-project2-quizzy#21]
if i put space in question, and create answer and valide one the question is accepted and go in DB

**Comment by Benjamin-51** [comment]
Since questions are curated by the admin, question that aren't valid can be discarded.
It's true that we could verify if a question have at least one character, but a malicious person could also send one character and it would be a arms race into pre-validating the question. Do you have any suggestions?

**Comment by MorganeL-pro** [comment]
Thanks for your message. 
We solved this problem.
